version: "3"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    hostname: mysqldb
    environment:
      MYSQL_DATABASE: fashion
      MYSQL_ROOT_PASSWORD: 1224
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./recommendation-system:/recommendation-system
    depends_on:
      - mysqldb
      - redis
      - zookeeper
      - kafka
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysqldb:3306 -s -t 100
        java -jar /app.jar
  
