spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
    serialization-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/fashion?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1224
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight: true
        default_batch_fetch_size: 100
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: 34.47.98.129:9094
    consumer:
      topic: chatting


file:
  profileImagePath: temp/profileImageUpload/
  postImagePath: temp/postImageUpload/
userCategory:
  maxUseScores : 50
  maxCategoryCount : 8
  filePath : category_scores/

autoTraining: recommendation-system/dist/train.exe


server:
  port: 8080